### ISSUE TITLE
Different tokens per environment?

### ISSUE THREAD

**Issue by ErebusBat** [NickRimmer/insomnia-plugin-oa2-mate#5]
Is it possible to have oa2-mate keep different tokens / sessions per environment?

I have three main environments that I work in:

1. Local Dev
2. Staging
3. Production

Each requiring a different token / session.  Right now I handle this by setting up each client id/secret/redirect_uris as environment variables; however when switching back and forth I have to re-authenticate.

It would be much easier if it would keep the session in each environment so I could just switch the environment and compare say production to local dev.

**Comment by NickRimmer** [comment]
Great idea! I think it should be possible, let me check it

**Comment by ErebusBat** [comment]
Hooray!

I am mostly a BE guy so my JS skills are lacking... but willing to beta test or document to help out

**Comment by NickRimmer** [comment]
The build from PR changes I've created for this feature, if you want to test it. I do not want to push it right now, but tomorrow or couple of days later. Want to test it myself for some time before release

[insomnia-plugin-oa2-mate.zip](https://github.com/NickRimmer/insomnia-plugin-oa2-mate/files/12062116/insomnia-plugin-oa2-mate.zip)

**Comment by NickRimmer** [comment]
A new option added for environments (;

![image](https://github.com/NickRimmer/insomnia-plugin-oa2-mate/assets/1754265/1aff2113-f4f3-4f44-a33f-5d9db02ff095)

**Comment by ErebusBat** [comment]
@NickRimmer AWESOME!   What can I do to test this?

**Comment by NickRimmer** [comment]
In case of windows, Insomnia plugins stored this path `%AppData%/Insomnia/plugins`
you can replace `insomnia-plugin-oa2-mate` folder from this zip

**Comment by NickRimmer** [comment]
Looks good for me, PR completed. To update already installed plugin, just install it again by name `insomnia-plugin-oa2-mate`.

I hope my another PR with plugins update logic will be approved to make it easier in a future (;
https://github.com/Kong/insomnia/pull/6160

**Comment by ErebusBat** [comment]
Thank you so much!

I have installed the update and see the option... however I am still having to refresh / re-authenticate when switching environments.

Perhaps I am doing something wrong?

I have my token setup in my base environment:

![Insomnia](https://github.com/NickRimmer/insomnia-plugin-oa2-mate/assets/93973/3b6a66a0-1a32-44b9-8b9b-d853039e7968)

However when I select the env specific option, then click done, it does not preserve it:
![Insomnia](https://github.com/NickRimmer/insomnia-plugin-oa2-mate/assets/93973/489919d0-ddca-49cb-ba49-e2aad34f7cca)

Because it isn't preserved I assume that is why I am seeing the previous behaviour.

Should I be editing the option in another manner?

**Comment by NickRimmer** [comment]
Hi @ErebusBat, yeah... I faced the same. But this is some Insomnia issue, when you change any template tag settings, click around a bit before clicking Done

**Comment by ErebusBat** [comment]
@NickRimmer That worked, thank you!

This is a HUGE help!
