### ISSUE TITLE
Plugin error 'getState' after Insomnia update 

### ISSUE THREAD

**Issue by ldamet** [NickRimmer/insomnia-plugin-oa2-mate#7]
Hello,

This morning I got an Insomnia update and since then the plugin does not work. The following error is displayed in the environment:
![image](https://github.com/NickRimmer/insomnia-plugin-oa2-mate/assets/1410076/95d2b7e2-6722-4484-94a0-36bde57fe7f7)

Infos about insomnia:
![image](https://github.com/NickRimmer/insomnia-plugin-oa2-mate/assets/1410076/f9a26014-6029-4aaf-ae6d-bdc292c97b76)

Cheers

**Comment by ldamet** [comment]
I managed to patch the plugin locally. I found that the plugin uses the reactContainer object to retrieve workspace/environment info to save/retrieve oauth2 token, and it seems stuff has moved around.

The current workspaceId can be found in:
root[parameter].memoizedState.element.props.router.state.loaderData[":workspaceId"].activeWorkspace._id

The current environmentId can be found in:
root[parameter].memoizedState.element.props.router.state.loaderData[":workspaceId"].activeEnvironment._id


Ideally the plugin should not rely on internals to be stable, but I didn't find any clean solution to save the oauth2 token.

For the templating part we can just use the plugin context (ctx?.meta?.workspaceId and ctx?.context?.getEnvironmentId()).

**Comment by brandonmbanks** [comment]
@ldamet Would you mind sharing your solution or opening a PR to fix the problem? We also ran into this issue.

**Comment by ldamet** [comment]
@brandonmbanks I just opened a PR to fix the issue but I'm not sure this is the best solution for the original problem. I will leave that decision to the actual maintainer of the the plugin.

If you want to test my solution you can follow my instructions in the PR. If you don't want to actually clone+build the repo here is the generated index.js that works for me:
[quickfix.zip](https://github.com/NickRimmer/insomnia-plugin-oa2-mate/files/12440069/quickfix.zip)

Just copy the index.js file in your insomnia plugin folder (%APPDATA%/insomnia/plugins/insomnia-plugin-oa2-mate on windows) then restart insomnia.

**Comment by brandonmbanks** [comment]
Awesome. Thanks so much for doing this. I'll take a look!

**Comment by NickRimmer** [comment]
Oh... they broke so much with the last update. People will create fewer plugins if they will continue in this way...
