### ISSUE TITLE
Download issue for Windows machine 

### ISSUE THREAD

**Issue by anilkilickaplan** [NickRimmer/insomnia-plugin-oa2-mate#9]
I am getting the error mentioned below while trying to install the lugin from Insomnia Plugin Hub.
The system is Windows 11 x64

_Error: Error invoking remote method 'installPlugin': Error: Yarn error {"type":"error","data":"Received invalid response from npm."}

    at a.invoke (node:electron/js2c/renderer_init:2:7723)
    at async onSubmit (file:///C:/Users/A200270920/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:195:513)_

**Comment by marlenesco** [comment]
Same behavior in mac osx

**Comment by NickRimmer** [comment]
Hey! Just a heads-up that I'm closing old tickets and archiving this repo. I've started working on my own client, where I'll be applying all the ideas I wanted to bring here 😊

It's called [RestApia](https://www.restapia.app/). Feel free to check it out!
